### ISSUE TITLE
SFTP Dataset 

### ISSUE THREAD

**Issue by rajesh-ca** [Mmodarre/AzureDataFactoryHOL#19]
In 02-Linked_Services_Datasets_and_Integration_Runtimes, Step 12, the text indicates use of the SFTP linked service, but the screenshots all refer to the blob storage linked service.

Also, the preview data doesn't appear to work when referring to the SFTP linked service. The following error occurs immaterial of the use of parameters/fixed names or the compression type.
![image](https://user-images.githubusercontent.com/60890019/82660431-5ba5ab00-9bf8-11ea-8405-d3d18de005fe.png)

**Comment by tanmoycuat** [comment]
Related to this the WorldWideImporters/orders & WorldWideImporters/orderslines sftp are not working but for WorldWideImporters/customers it's working any reflection.  Can we sync with each other on this?

**Comment by mdrakiburrahman** [comment]
@rajesh-ca I ran into the same issue - it's because Data Factory is timing out since the orderlines parquet file is too big. 

I logged into the SFTP with FileZilla, and tried one of the customers files instead:
![image](https://user-images.githubusercontent.com/46581776/82732455-4786aa00-9cdb-11ea-8106-5fe3ce3d7707.png)
![image](https://user-images.githubusercontent.com/46581776/82732472-67b66900-9cdb-11ea-8adb-011cfa8b357f.png)

Works fine for preview from ADF:
![image](https://user-images.githubusercontent.com/46581776/82732482-78ff7580-9cdb-11ea-8a5c-d32f512382e9.png)

**Comment by Mmodarre** [comment]
This is interesting. I checked through the logs of the SFTP server and it didn't seem to have logged anything out of ordinary. Orderline files are approx 250MB and this shouldn't be a problem unless the tiny SFTP server we are running has been overloaded. I took some extra pre-cautions to stop DDOS and brute forcing attacks on the server. let me know if you still face the same issue

**Comment by tanmoycuat** [comment]
I tried retrieving Orders and Orderlines its not working. However Customers works nicely.
The error that I get is 

![image](https://user-images.githubusercontent.com/47568628/82799209-4dc18580-9e97-11ea-9ebf-7a59c0c34509.png)

**Comment by Mmodarre** [comment]
You are right there is no file for those dates. That is why we use the get-metadata activity to get file lists and then loop through it.

![image](https://user-images.githubusercontent.com/23395096/82847764-46e85080-9f33-11ea-8b81-b9aa30ec984d.png)

![image](https://user-images.githubusercontent.com/23395096/82847775-549dd600-9f33-11ea-94cf-35d9abb2d40e.png)

**Comment by Mmodarre** [comment]
Adding this note for future reference:

SFTP server is only accessible through ADF. Due to brute force and DDoS attacks, I had to close the network to public internet.

so **Don't try accessing the SFTP from your local machine using an SFTP client as it will not work.**
